eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false       # Not a client, don't register with yourself
    fetchRegistry: false

server:
  port: 1111                        # HTTP (Tomcat) port
